---
title: "Sentiment Analysis"
author: "created by KBS"
date: '2019 9 18 '
output: html_document
---

# 감정분석 - Sentiment Analysis(Data : YG Entertainment 기사)

## 01. 데이터 준비 및 사전 준비
install.packages('wordcloud')
install.packages('KoNLP')
```{r}
rm(list=ls())

library(wordcloud)
library(KoNLP)

useSejongDic()

fname <- 'C:/R/sb19-01/R_Class/6일차/YG.txt'
roadi <- readLines(fname)
```

## 02. 긍정단어 부정단어 불러오기
```{r}
pos.words <- scan('C:/R/sb19-01/R_Class/6일차/pos_kor_words.txt',
                 what='character', comment.char=';')
neg.words <- scan('C:/R/sb19-01/R_Class/6일차/neg_kor_words.txt',
                 what='character', comment.char=';')
```

## 03. 불러온 텍스트 전처리
```{r}
sentence <- roadi

library(plyr)

# 구두점 문자, ! " # $ % & ’ ( ) * + , - . / : ; < = > ? @ [  ] ^ _ ` { | } ~. 제거
sentence <- gsub('[[:punct:]]', '', sentence)

# \n, \r 같은 제어문자 등 제거
sentence <- gsub('[[:cntrl:]]', '', sentence)

# 숫자 제거
sentence <- gsub('\\d+', '', sentence)

# 줄수
length(sentence)
```

## 04. 명사 추출
```{r}
wordlist <- sapply(sentence, extractNoun, USE.NAMES=F)
words <- unlist(wordlist) # 단어를 하나의 벡터로
head(words)
length(words)
```

## 05. 감성 분석을 위한 점수 확인
```{r}
pos.matches <- match(words, pos.words)
head(pos.matches)
neg.matches <- match(words, neg.words)
head(neg.matches)

pos.matches <- !is.na(pos.matches)
neg.matches <- !is.na(neg.matches)

sum(pos.matches)
sum(neg.matches)

score <- sum(pos.matches) - sum(neg.matches)

pos_word <- words[pos.matches ]
neg_word <- words[neg.matches ]

pos_cnt <- table(pos_word)
neg_cnt <- table(neg_word)

pos_cnt_sort <- sort(pos_cnt, decreasing = T)
neg_cnt_sort <- sort(neg_cnt, decreasing = T)
```

## 06. 긍정단어, 부정단어 TOP 5
```{r}
barplot(pos_cnt_sort[5:0], main='긍정 단어 TOP 5', horiz=T, col=c("green", "blue", "yellow"))
barplot(neg_cnt_sort[5:0], main="부정 단어 TOP 5", horiz=T, col=c("green", "blue", "yellow"))
```

## 07. WordCloud
install.packages('wordcloud2')
```{r}
library(wordcloud2)
library(RColorBrewer)

palette = brewer.pal(8, 'Set2')

base_word2 <- as.data.frame(pos_cnt, stringsAsFactors=F)

wordcloud2(data=base_word2, fontFamily='나눔바른고딕')
```